config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'users/delete_account', to: 'users#delete_account', as: 'delete_account'

  devise_for :users

  resources :projects, shallow: true do
    resources :sections, except: :index, shallow: true do
      resources :cards, except: :index, shallow: true do
        resources :comments, except: :index, shallow: true
      end
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  belongs_to :leader, class_name: 'User', optional: true
  belongs_to :section
  belongs_to :color
  delegate :project, to: :section

  has_many :comments, dependent: :destroy
  has_many :card_teamings, dependent: :destroy
  has_many :members, through: :card_teamings, dependent: :destroy
  has_many :card_taggings, dependent: :destroy
  has_many :tags, through: :card_taggings, dependent: :destroy
  has_many :comment_taggings, dependent: :destroy
  has_many :comment_tags, through: :comment_taggings, source: :tag, dependent: :destroy

  # Validations
  validates :title, :status, presence: true
end

app/models/card_tagging.rb
class CardTagging < ApplicationRecord
  belongs_to :user
  belongs_to :card
  belongs_to :tag
end

app/models/card_teaming.rb
class CardTeaming < ApplicationRecord
  belongs_to :user
  belongs_to :member, class_name: 'User'
  belongs_to :card
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :user
  belongs_to :member, class_name: 'User'
  belongs_to :project
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :sections
  has_many :cards

  # Validations
  validates :name, :hexcode, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :card
  delegate :section, to: :card
  delegate :project, to: :card

  has_many :responses
  has_many :comment_taggings, dependent: :destroy
  has_many :tags, through: :comment_taggings, dependent: :destroy

  # Validations
  validates :content, presence: true
end

app/models/comment_tagging.rb
class CommentTagging < ApplicationRecord
  belongs_to :card
  belongs_to :comment
  belongs_to :tag
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  # Validations
  validates :notification_action, :notification_target, presence: true
end

app/models/privilege.rb
class Privilege < ApplicationRecord
  belongs_to :user
  belongs_to :admin, class_name: 'User'
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :sections, dependent: :destroy
  has_many :cards, through: :sections, dependent: :destroy
  has_many :collaborations, dependent: :destroy
  has_many :members, through: :collaborations, dependent: :destroy
  has_many :privileges, dependent: :destroy
  has_many :admins, through: :privileges, dependent: :destroy

  # Validations
  validates :title, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  # Validations
  validates :content, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :leader, class_name: 'User', optional: true
  belongs_to :color

  has_many :cards, dependent: :destroy
  has_many :section_teamings, dependent: :destroy
  has_many :members, through: :section_teamings, dependent: :destroy
  has_many :section_taggings, dependent: :destroy
  has_many :tags, through: :section_taggings, dependent: :destroy

  # Validations
  validates :title, presence: true
end

app/models/section_tagging.rb
class SectionTagging < ApplicationRecord
  belongs_to :user
  belongs_to :section
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :section_taggings
  has_many :sections, through: :section_taggings
  has_many :card_taggings
  has_many :cards, through: :card_taggings
  has_many :comment_taggings
  has_many :comments, through: :comment_taggings

  # Validations
  validates :name, presence: true
end

app/models/user.rb
require 'open-uri'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # after_create :set_default_avatar

  # Relations
  has_many :privileges
  has_many :admin_privileges, class_name: 'Privilege', foreign_key: 'admin_id'

  has_many :projects
  has_many :project_memberships, class_name: 'Collaboration', foreign_key: 'member_id'

  has_many :sections
  has_many :section_taggings
  has_many :section_memberships, class_name: 'SectionTeaming', foreign_key: 'member_id'
  has_many :section_leaderships, class_name: 'Section', foreign_key: 'leader_id'

  has_many :cards
  has_many :card_taggings
  has_many :card_memberships, class_name: 'CardTeaming', foreign_key: 'member_id'
  has_many :card_leaderships, class_name: 'Card', foreign_key: 'leader_id'

  has_many :comments
  has_many :notifications
  has_many :responses

  has_one_attached :photo

  # Validations
  validates :first_name, :last_name, :username, :email, presence: true
  validates :username, :email, uniqueness: true
  # validates :email, confirmation: true

  validates :first_name, :last_name,
            format: { with: /[A-Za-z]+/,
                      message: 'should contain only letters' }

  validates :username,
            format: { with: /\A(?=[a-zA-Z0-9._-]{5,20}$)(?!.*[_.]{2})[^_.].*[^_.]\z/,
                      message: 'should contain between 5 and 20 characters' }

  # def set_default_avatar
  #   return if photo.attached?

  #   avatar_url = "https://api.adorable.io/avatars/285/#{id}projecttracker.png"
  #   avatar = URI.open(avatar_url)
  #   photo.attach(io: avatar, filename: "#{username}.png", content_type: 'image/png')
  # end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[show edit update destroy]

  def show
    authorize @section
  end

  def new
    @section = Section.new
    @project = Project.find(params[:project_id])
    authorize @project, :privilege_check
  end

  def create
    @section = Section.new(section_params)
    @section.user = current_user
    @section.project = Project.find(params[:project_id])
    authorize @section.project, :privilege_check
    if @section.save
      add_user_as_section_member unless @section.members.include?(current_user)
      add_leader_as_section_member unless @section.leader == @section.user && @section.members.include?(@section.leader)
      redirect_to @section.project, notice: 'Section successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @section
  end

  def update
    authorize @section
    if @section.update(section_params)
      redirect_to @section, notice: 'Section successfully edited.'
    else
      render :edit
    end
  end

  def destroy
    authorize @section
    project = @section.project
    @section.destroy
    redirect_to project_path(project), notice: 'Section was deleted.'
  end

  private

  def section_params
    params.require(:section).permit(:title,
                                    :description,
                                    :start_date,
                                    :end_date,
                                    :leader_id,
                                    :color_id)
  end

  def set_section
    @section = Section.find_by(id: params[:id])
    redirect_to dashboard_path, notice: 'Section not found.' if @section.nil?
  end

  def add_user_as_section_member
    SectionTeaming.create(user_id: current_user.id,
                          member_id: current_user.id,
                          section_id: @section.id)
  end

  def add_leader_as_section_member
    SectionTeaming.create(user_id: current_user.id,
                          member_id: @section.leader.id,
                          section_id: @section.id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sections/edit.html.erb
<p><%= link_to "back to project", project_path(Section.find(params[:id]).project) %></p>

<h2>Update Section</h2>

<%= form_with(model: @section, local: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :start_date %>
  <%= f.date_select :start_date %>

  <%= f.label :end_date %>
  <%= f.date_select :end_date %>

  <%= f.label :leader %>
  <%= collection_select(:section, :leader_id, @section.project.members, :id, :username) %>

  <%= f.label :color %>
  <%= collection_select(:section, :color_id, Color.all, :id, :name) %>

  <%= f.submit "Update section" %>
<% end %>

app/views/sections/new.html.erb
<p><%= link_to "back to project", project_path(params[:project_id]) %></p>

<h2>New Section</h2>

<%= form_with(model: @section, url: project_sections_path(params[:project_id]), local: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :start_date %>
  <%= f.date_select :start_date %>

  <%= f.label :end_date %>
  <%= f.date_select :end_date %>

  <%= f.label :leader %>
  <%= collection_select(:section, :leader_id, Project.find(params[:project_id]).members, :id, :username) %>

  <%= f.label :color %>
  <%= collection_select(:section, :color_id, Color.all, :id, :name) %>

  <%= f.submit "Create section" %>
<% end %>

app/views/sections/show.html.erb
<p><%= link_to "back to project", project_path(Section.find(params[:id]).project) %></p>

<% if policy(@section).edit? %>
  <%= link_to edit_section_path(@section) do %>
    <span><i class="fas fa-edit"></i> Edit section</span>
  <% end %>
<% end %>

<% if policy(@section).destroy? %>
  <%= link_to section_path(@section), method: :delete, data: { confirm: 'Are you sure?' } do %>
    <span> <i class="far fa-trash-alt"></i> Delete section</span>
  <% end %>
<% end %>

<h1>Section: <%= @section.title %></h1>
<p><%= @section.description %></p>

<p>Team: <% @section.members.each do |member| %>
    <%= member.username %>
  <% end %></p>

<% if policy(@section).new_card %>
  <%= link_to new_section_card_path(@section) do %>
    <span><i class="fas fa-plus"></i> New card</span>
  <% end %>
<% end %>

<% @section.cards.each do |card| %>
  <hr>

  <h4 style="color: <%= card.color.name %>;"><strong><%= link_to card.title, card_path(card) %></strong></h4>
  <p><%= card.description %></p>
  <p><%= "Leader: #{card.leader.username}" if card.leader %></p>

  <p>Team: <% card.members.each do |member| %>
      <%= member.username %>
    <% end %></p>

  <p><%= "Category: #{card.category} | Status: #{card.status} | Priority: #{card.priority}" %></p>
<% end %>