config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'users/delete_account', to: 'users#delete_account', as: 'delete_account'

  devise_for :users

  resources :projects, shallow: true do
    resources :sections, except: :index, shallow: true do
      resources :cards, except: :index, shallow: true do
        resources :comments, except: :index, shallow: true
      end
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  belongs_to :leader, class_name: 'User', optional: true
  belongs_to :section
  belongs_to :color
  delegate :project, to: :section

  has_many :comments, dependent: :destroy
  has_many :card_teamings, dependent: :destroy
  has_many :members, through: :card_teamings, dependent: :destroy
  has_many :card_taggings, dependent: :destroy
  has_many :tags, through: :card_taggings, dependent: :destroy
  has_many :comment_taggings, dependent: :destroy
  has_many :comment_tags, through: :comment_taggings, source: :tag, dependent: :destroy

  # Validations
  validates :title, :status, presence: true
end

app/models/card_tagging.rb
class CardTagging < ApplicationRecord
  belongs_to :user
  belongs_to :card
  belongs_to :tag
end

app/models/card_teaming.rb
class CardTeaming < ApplicationRecord
  belongs_to :user
  belongs_to :member, class_name: 'User'
  belongs_to :card
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :user
  belongs_to :member, class_name: 'User'
  belongs_to :project
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :sections
  has_many :cards

  # Validations
  validates :name, :hexcode, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :card
  delegate :section, to: :card
  delegate :project, to: :card

  has_many :responses
  has_many :comment_taggings, dependent: :destroy
  has_many :tags, through: :comment_taggings, dependent: :destroy

  # Validations
  validates :content, presence: true
end

app/models/comment_tagging.rb
class CommentTagging < ApplicationRecord
  belongs_to :card
  belongs_to :comment
  belongs_to :tag
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  # Validations
  validates :notification_action, :notification_target, presence: true
end

app/models/privilege.rb
class Privilege < ApplicationRecord
  belongs_to :user
  belongs_to :admin, class_name: 'User'
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :sections, dependent: :destroy
  has_many :cards, through: :sections, dependent: :destroy
  has_many :collaborations, dependent: :destroy
  has_many :members, through: :collaborations, dependent: :destroy
  has_many :privileges, dependent: :destroy
  has_many :admins, through: :privileges, dependent: :destroy

  # Validations
  validates :title, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  # Validations
  validates :content, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :leader, class_name: 'User', optional: true
  belongs_to :color

  has_many :cards, dependent: :destroy
  has_many :section_teamings, dependent: :destroy
  has_many :members, through: :section_teamings, dependent: :destroy
  has_many :section_taggings, dependent: :destroy
  has_many :tags, through: :section_taggings, dependent: :destroy

  # Validations
  validates :title, presence: true
end

app/models/section_tagging.rb
class SectionTagging < ApplicationRecord
  belongs_to :user
  belongs_to :section
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :section_taggings
  has_many :sections, through: :section_taggings
  has_many :card_taggings
  has_many :cards, through: :card_taggings
  has_many :comment_taggings
  has_many :comments, through: :comment_taggings

  # Validations
  validates :name, presence: true
end

app/models/user.rb
require 'open-uri'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # after_create :set_default_avatar

  # Relations
  has_many :privileges
  has_many :admin_privileges, class_name: 'Privilege', foreign_key: 'admin_id'

  has_many :projects
  has_many :project_memberships, class_name: 'Collaboration', foreign_key: 'member_id'

  has_many :sections
  has_many :section_taggings
  has_many :section_memberships, class_name: 'SectionTeaming', foreign_key: 'member_id'
  has_many :section_leaderships, class_name: 'Section', foreign_key: 'leader_id'

  has_many :cards
  has_many :card_taggings
  has_many :card_memberships, class_name: 'CardTeaming', foreign_key: 'member_id'
  has_many :card_leaderships, class_name: 'Card', foreign_key: 'leader_id'

  has_many :comments
  has_many :notifications
  has_many :responses

  has_one_attached :photo

  # Validations
  validates :first_name, :last_name, :username, :email, presence: true
  validates :username, :email, uniqueness: true
  # validates :email, confirmation: true

  validates :first_name, :last_name,
            format: { with: /[A-Za-z]+/,
                      message: 'should contain only letters' }

  validates :username,
            format: { with: /\A(?=[a-zA-Z0-9._-]{5,20}$)(?!.*[_.]{2})[^_.].*[^_.]\z/,
                      message: 'should contain between 5 and 20 characters' }

  # def set_default_avatar
  #   return if photo.attached?

  #   avatar_url = "https://api.adorable.io/avatars/285/#{id}projecttracker.png"
  #   avatar = URI.open(avatar_url)
  #   photo.attach(io: avatar, filename: "#{username}.png", content_type: 'image/png')
  # end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def show
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project
    if @project.save
      add_user_as_member
      add_user_as_admin
      redirect_to @project, notice: 'Project successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @project
  end

  def update
    authorize @project
    if @project.update(project_params)
      redirect_to @project, notice: 'Project successfully edited.'
    else
      render :edit
    end
  end

  def destroy
    authorize @project
    @project.destroy
    redirect_to dashboard_path, notice: 'Project was deleted.'
  end

  private

  def project_params
    params.require(:project).permit(:title,
                                    :description,
                                    :start_date,
                                    :end_date)
  end

  def set_project
    @project = Project.find_by(id: params[:id])
    redirect_to dashboard_path, notice: 'Project not found.' if @project.nil?
  end

  def add_user_as_member
    Collaboration.create(user_id: current_user.id,
                         member_id: current_user.id,
                         project_id: @project.id)
  end

  def add_user_as_admin
    Privilege.create(user_id: current_user.id,
                     admin_id: current_user.id,
                     project_id: @project.id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/edit.html.erb
<p><%= link_to "back to dashboard", dashboard_path %></p>

<h2>Update Project</h2>

<%= form_with(model: @project, local: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :start_date %>
  <%= f.date_select :start_date %>

  <%= f.label :end_date %>
  <%= f.date_select :end_date %>

  <%= f.submit "Update project" %>
<% end %>

app/views/projects/new.html.erb
<p><%= link_to "back to dashboard", dashboard_path %></p>

<h2>New Project</h2>

<%= form_with(model: @project, local: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :start_date %>
  <%= f.date_select :start_date %>

  <%= f.label :end_date %>
  <%= f.date_select :end_date %>

  <%= f.submit "Create project" %>
<% end %>

app/views/projects/show.html.erb
<p><%= link_to "back to dashboard", dashboard_path %></p>

<% if policy(@project).privilege_check %>
  <%= link_to new_project_section_path(@project) do %>
    <span><i class="fas fa-plus"></i> New section</span>
  <% end %>
<% end%>

<% if policy(@project).edit? %>
  <%= link_to edit_project_path(@project) do %>
    <span><i class="fas fa-edit"></i> Edit project</span>
  <% end %>
<% end %>

<% if policy(@project).destroy? %>
  <%= link_to project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } do %>
    <span> <i class="far fa-trash-alt"></i> Delete project</span>
  <% end %>
<% end %>

<h1>Project: <%= @project.title %></h1>
<p><%= @project.description %></p>
<p>Team: <% @project.members.each do |member| %>
    <%= member.username %>
  <% end %></p>

<% @project.sections.each do |section| %>
  <hr>
  <h4>Section: <strong><%= link_to section.title, section_path(section) %></strong></h4>
  <p><%= section.description %></p>
  <p><%= "Leader: #{section.leader.username}" if section.leader %></p>

  <p>Team: <% section.members.each do |member| %>
      <%= member.username %>
    <% end %></p>

  <p>Cards: <%= section.cards.count %></p>
<% end %>