config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'users/delete_account', to: 'users#delete_account', as: 'delete_account'

  devise_for :users

  resources :projects, shallow: true do
    resources :sections, except: :index, shallow: true do
      resources :cards, except: :index, shallow: true do
        resources :comments, except: :index, shallow: true
      end
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  belongs_to :leader, class_name: 'User', optional: true
  belongs_to :section
  belongs_to :color
  delegate :project, to: :section

  has_many :comments, dependent: :destroy
  has_many :card_teamings, dependent: :destroy
  has_many :members, through: :card_teamings, dependent: :destroy
  has_many :card_taggings, dependent: :destroy
  has_many :tags, through: :card_taggings, dependent: :destroy
  has_many :comment_taggings, dependent: :destroy
  has_many :comment_tags, through: :comment_taggings, source: :tag, dependent: :destroy

  # Validations
  validates :title, :status, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[show edit update destroy]

  def show
    @comment = Comment.new
    authorize @card
  end

  def new
    @card = Card.new
    @section = Section.find(params[:section_id])
    authorize @section, :new_card
  end

  def create
    @card = Card.new(card_params)
    @card.user = current_user
    @card.section = Section.find(params[:section_id])
    authorize @card.section, :new_card
    if @card.save
      add_user_as_member unless @card.members.include?(current_user)
      add_user_as_section_member unless @card.section.members.include?(current_user)
      add_leader_as_member unless @card.leader == @card.user && @card.members.include?(@card.leader)
      add_leader_as_section_member unless @card.section.members.include?(@card.leader)
      redirect_to @card.section, notice: 'Card successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @card
  end

  def update
    authorize @card
    if @card.update(card_params)
      redirect_to @card, notice: 'Card successfully edited.'
    else
      render :edit
    end
  end

  def destroy
    authorize @card
    section = @card.section
    @card.destroy
    redirect_to section_path(section), notice: 'Card was deleted.'
  end

  private

  def card_params
    params.require(:card).permit(:title,
                                 :description,
                                 :start_date,
                                 :end_date,
                                 :leader_id,
                                 :color_id,
                                 :priority,
                                 :status,
                                 :category)
  end

  def set_card
    @card = Card.find_by(id: params[:id])
    redirect_to dashboard_path, notice: 'Card not found.' if @card.nil?
  end

  def add_user_as_member
    CardTeaming.create(user_id: current_user.id,
                       member_id: current_user.id,
                       card_id: @card.id)
  end

  def add_leader_as_member
    CardTeaming.create(user_id: current_user.id,
                       member_id: @card.leader.id,
                       card_id: @card.id)
  end

  def add_user_as_section_member
    SectionTeaming.create(user_id: current_user.id,
                          member_id: current_user.id,
                          section_id: @card.section.id)
  end

  def add_leader_as_section_member
    SectionTeaming.create(user_id: current_user.id,
                          member_id: @card.leader.id,
                          section_id: @card.section.id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<p><%= link_to "back to section", section_path(Card.find(params[:id]).section) %></p>

<h2>Update Card</h2>

<%= form_with(model: @card, local: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :start_date %>
  <%= f.date_select :start_date %>

  <%= f.label :end_date %>
  <%= f.date_select :end_date %>

  <%= f.label :priority %>
  <%= f.select(:priority, options_for_select(["low", "medium", "high"], Card.find(params[:id]).priority)) %>

  <%= f.label :status %>
  <%= f.select(:status, options_for_select(["new", "in progress", "done"], Card.find(params[:id]).status)) %>

  <%= f.label :category %>
  <%= f.select(:category, options_for_select(["issue", "feature"], Card.find(params[:id]).category)) %>

  <%= f.label :leader %>
  <%= collection_select(:card, :leader_id, Card.find(params[:id]).members, :id, :username) %>

  <%= f.label :color %>
  <%= collection_select(:card, :color_id, Color.all, :id, :name) %>

  <%= f.submit "Update card" %>
<% end %>

app/views/cards/new.html.erb
<p><%= link_to "back to section", section_path(params[:section_id]) %></p>

<h2>New Card</h2>

<%= form_with(model: @card, url: section_cards_path(params[:section_id]), local: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :start_date %>
  <%= f.date_select :start_date %>

  <%= f.label :end_date %>
  <%= f.date_select :end_date %>

  <%= f.label :priority %>
  <%= f.select(:priority, options_for_select(["low", "medium", "high"])) %>

  <%= f.label :status %>
  <%= f.select(:status, options_for_select(["new", "in progress", "done"])) %>

  <%= f.label :category %>
  <%= f.select(:category, options_for_select(["issue", "feature"])) %>

  <%= f.label :leader %>
  <%= collection_select(:card, :leader_id, Section.find(params[:section_id]).members, :id, :username) %>

  <%= f.label :color %>
  <%= collection_select(:card, :color_id, Color.all, :id, :name) %>

  <%= f.submit "Create card" %>
<% end %>

app/views/cards/show.html.erb
<p><%= link_to "back to section", section_path(Card.find(params[:id]).section) %></p>

<% if policy(@card).privilege_check || policy(@card).section_membership_check %>
  <%= link_to new_card_comment_path(@card) do %>
    <span><i class="fas fa-plus"></i> New comment</span>
  <% end %>
<% end %>

<% if policy(@card).edit? %>
  <%= link_to edit_card_path(@card) do %>
    <span><i class="fas fa-edit"></i> Edit card</span>
  <% end %>
<% end %>

<% if policy(@card).destroy? %>
  <%= link_to card_path(@card), method: :delete, data: { confirm: 'Are you sure?' } do %>
    <span> <i class="far fa-trash-alt"></i> Delete card</span>
  <% end %>
<% end %>

<h1>Card: <%= @card.title %></h1>
<p><%= @card.description %></p>
<p><%= "Category: #{@card.category} | Status: #{@card.status} | Priority: #{@card.priority}" %></p>
<p><%= "Leader: #{@card.leader.username}" if @card.leader %></p>
<p>Team: <% @card.members.each do |member| %>
    <%= member.username %>
  <% end %></p>

<%= render "comments/new" %>

<% @card.comments.each do |comment| %>
  <hr>
  <p><%= "#{comment.user.username}: #{comment.content}" %>
    <% if policy(comment).edit?  %>
      <%= link_to edit_comment_path do %>
        <i class="far fa-edit"></i>
      <% end %>
    <% end %>
  </p>
  <hr>
<% end %>


<%# link_to render(:partial => 'shared/logo'), root_url %>